spring:
  application:
    name: quantcrux-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/quantcrux
    username: quant_user
    password: quant_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        globally_quoted_identifiers: false
        jdbc:
          lob:
            non_contextual_creation: true
        type:
          preferred_json_mapper: jackson
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:}
            client-secret: ${GITHUB_CLIENT_SECRET:}

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:quantcrux-super-secret-key-for-development-only-change-in-production}
  expiration: 86400000 # 24 hours
  refresh-expiration: 2592000000 # 30 days

finnhub:
  api:
    key: ${FINNHUB_API_KEY:d27nkopr01qr2iasmtfgd27nkopr01qr2iasmtg0}

# External API Configuration
external-apis:
  finnhub:
    base-url: https://finnhub.io/api/v1
    timeout: 10s
    rate-limit:
      requests-per-minute: 60
      requests-per-day: 1000
  twelvedata:
    base-url: https://api.twelvedata.com/v1
    timeout: 10s
    rate-limit:
      requests-per-minute: 8
      requests-per-day: 800
  coingecko:
    base-url: https://api.coingecko.com/api/v3
    timeout: 10s
    rate-limit:
      requests-per-minute: 50
      requests-per-day: 1000

cors:
  allowed-origins: http://localhost:5173,http://localhost:3000
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

logging:
  level:
    com.quantcrux: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE